import { useEffect, useState } from "react";
import { CheckCircle2, ChevronDown, Factory, HardHat, Mail, MapPin, Menu, Phone, ShieldCheck, Wrench, X, Zap } from "lucide-react";

const asset = (path: string) => `${import.meta.env.BASE_URL}${path.replace(/^\/+/, "")}`;
const whatsapp = "https://wa.me/526313185564";
const services = [
  { icon: Wrench, title: "Mantenimiento industrial", text: "Diagnóstico, mantenimiento preventivo y correctivo para maquinaria e instalaciones de planta." },
  { icon: Factory, title: "Moldeo por inyección", text: "Soporte técnico para procesos de inyección, moldes, periféricos y continuidad de producción." },
  { icon: Zap, title: "Instalaciones y HVAC", text: "Adecuaciones eléctricas, ventilación, climatización y servicios auxiliares industriales." },
  { icon: HardHat, title: "Fabricación y obra civil", text: "Estructuras, plataformas, herrería, montaje y adecuación de espacios productivos." },
];
const projects = [
  { image: "/proyectos/s22/fabricacion-mesa-industrial.jpg", title: "Fabricación industrial", label: "Necesidad", detail: "Mesa de trabajo robusta para operación en planta.", work: "Fabricación, soldadura, acabado y preparación para servicio." },
  { image: "/proyectos/s22/maquinado-precision.jpg", title: "Maquinado de precisión", label: "Alcance", detail: "Fabricación y ajuste de componentes metálicos.", work: "Revisión dimensional y acabado orientado a la aplicación." },
  { image: "/proyectos/s22/instalacion-ducto-industrial.jpg", title: "Instalación en planta", label: "Trabajo", detail: "Montaje de ductería y soportes en área industrial.", work: "Planeación de maniobra, instalación y revisión final." },
];
const faqs = [
  ["¿Qué tipo de empresas atienden?", "Principalmente operaciones de manufactura, plásticos, automotriz, electrónica, almacenes y servicios industriales en Nogales y otras ciudades de Sonora."],
  ["¿Cómo solicito una evaluación?", "Puede describir su necesidad por WhatsApp, teléfono o correo. Con esa información coordinamos una visita o una revisión técnica."],
  ["¿Trabajan dentro de planta?", "Sí. Antes de cada intervención se revisan alcance, accesos, riesgos, permisos y condiciones de trabajo aplicables."],
  ["¿Entregan evidencia del servicio?", "Cuando el alcance lo requiere, integramos fotografías, hallazgos, actividades realizadas y recomendaciones de seguimiento."],
];

function App() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [faqOpen, setFaqOpen] = useState<number | null>(0);
  useEffect(() => { const close = () => setMenuOpen(false); window.addEventListener("hashchange", close); return () => window.removeEventListener("hashchange", close); }, []);
  const sendRequest = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const data = new FormData(event.currentTarget);
    const text = ["SOLICITUD DE SERVICIO SGI", `Nombre: ${data.get("name")}`, `Empresa: ${data.get("company") || "No indicada"}`, `Correo: ${data.get("email")}`, `Teléfono: ${data.get("phone") || "No indicado"}`, `Servicio: ${data.get("service")}`, `Necesidad: ${data.get("message")}`].join("\n");
    window.open(`${whatsapp}?text=${encodeURIComponent(text)}`, "_blank", "noopener,noreferrer");
  };
  return <div className="sgi-site">
    <header className="site-header"><a className="brand" href="#inicio" aria-label="Ir al inicio de SGI"><img src={asset("/logo-sgi.png")} alt="SGI Servicios Generales de Ingeniería" /></a><nav className={menuOpen ? "nav-open" : ""} aria-label="Navegación principal">{[["Servicios","servicios"],["Proyectos","proyectos"],["Proceso","proceso"],["Nosotros","nosotros"],["Contacto","contacto"]].map(([label,id]) => <a key={id} href={`#${id}`}>{label}</a>)}<a className="nav-cta" href={`${whatsapp}?text=${encodeURIComponent("Hola SGI, necesito apoyo para un servicio industrial.")}`} target="_blank" rel="noreferrer">Solicitar atención</a></nav><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? "Cerrar menú" : "Abrir menú"} aria-expanded={menuOpen}>{menuOpen ? <X /> : <Menu />}</button></header>
    <main>
      <section id="inicio" className="hero"><div className="hero-copy"><span className="eyebrow">Ingeniería y servicios industriales · Nogales, Sonora</span><h1>Soluciones industriales para mantener su operación en marcha</h1><p>Integramos mantenimiento, fabricación, instalaciones, HVAC, obra civil y soporte para moldeo por inyección en un solo equipo de atención.</p><div className="hero-actions"><a className="button primary" href={`${whatsapp}?text=${encodeURIComponent("Hola SGI, quiero solicitar una evaluación para mi proyecto.")}`} target="_blank" rel="noreferrer">Solicitar evaluación</a><a className="button secondary" href="#proyectos">Ver trabajo realizado</a></div><ul className="hero-proof"><li><CheckCircle2 />Alcance definido</li><li><CheckCircle2 />Trabajo en planta</li><li><CheckCircle2 />Evidencia de servicio</li></ul></div><figure className="hero-image"><img src={asset("/proyectos/s22/maniobra-en-planta.jpg")} alt="Equipo realizando una maniobra industrial en planta" fetchPriority="high" /><figcaption>Atención técnica y ejecución en campo</figcaption></figure></section>
      <section id="servicios" className="section"><div className="section-heading"><span className="eyebrow">Capacidad técnica</span><h2>Servicios que se adaptan a su operación</h2><p>Definimos cada alcance según las condiciones reales de su planta, prioridades y requisitos de seguridad.</p></div><div className="service-grid">{services.map(({icon:Icon,title,text}) => <article className="service-card" key={title}><Icon /><h3>{title}</h3><p>{text}</p></article>)}</div></section>
      <section id="proyectos" className="section projects-section"><div className="section-heading"><span className="eyebrow">Evidencia fotográfica SGI</span><h2>Trabajo realizado en campo y taller</h2><p>Una muestra del tipo de fabricación, maquinado e instalación que ejecutamos. El alcance final se documenta para cada proyecto.</p></div><div className="project-grid">{projects.map(p => <article className="project-card" key={p.title}><img src={asset(p.image)} alt={p.title} loading="lazy" /><div><h3>{p.title}</h3><dl><dt>{p.label}</dt><dd>{p.detail}</dd><dt>Ejecución</dt><dd>{p.work}</dd></dl></div></article>)}</div></section>
      <section id="proceso" className="section process-section"><div className="section-heading"><span className="eyebrow">Método de trabajo</span><h2>De la necesidad a una entrega verificable</h2></div><ol className="process-grid">{[["01","Diagnóstico","Revisamos la necesidad, el entorno y las restricciones de operación."],["02","Propuesta","Definimos alcance, materiales, tiempos estimados y condiciones."],["03","Ejecución","Coordinamos el trabajo con seguridad, orden y comunicación."],["04","Entrega","Revisamos funcionamiento y compartimos evidencia cuando aplica."]].map(([n,t,d]) => <li key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></li>)}</ol><div className="safety-callout"><ShieldCheck /><div><h3>Seguridad integrada al servicio</h3><p>Antes de intervenir revisamos riesgos, accesos, permisos y equipo de protección conforme al alcance y a los lineamientos de cada instalación.</p></div></div></section>
      <section id="nosotros" className="section about-section"><div><span className="eyebrow">Acerca de SGI</span><h2>Un solo punto de contacto para necesidades industriales diversas</h2><p>SGI es un equipo de servicios generales de ingeniería con base en Nogales, Sonora. Reunimos capacidades mecánicas, eléctricas, de fabricación e instalación para resolver proyectos sin fragmentar la coordinación entre múltiples proveedores.</p><p>Nuestro enfoque es práctico: entender el problema, acordar el alcance, ejecutar con orden y dejar información útil para la continuidad de la operación.</p></div><div className="capability-list"><h3>Sectores que atendemos</h3>{["Manufactura y maquiladora","Plásticos y moldeo por inyección","Automotriz y electrónica","Almacenes e infraestructura industrial"].map(x => <span key={x}><CheckCircle2 />{x}</span>)}<p className="brand-note">Trabajamos con equipos y componentes de distintas marcas según la instalación del cliente. Las marcas pertenecen a sus respectivos titulares.</p></div></section>
      <section className="section faq-section"><div className="section-heading"><span className="eyebrow">Preguntas frecuentes</span><h2>Lo esencial antes de comenzar</h2></div><div className="faq-list">{faqs.map(([q,a],i) => <article key={q}><button onClick={() => setFaqOpen(faqOpen === i ? null : i)} aria-expanded={faqOpen === i}>{q}<ChevronDown className={faqOpen === i ? "rotated" : ""} /></button>{faqOpen === i && <p>{a}</p>}</article>)}</div></section>
      <section id="contacto" className="section contact-section"><div className="contact-copy"><span className="eyebrow">Contacto</span><h2>Cuéntenos qué necesita resolver</h2><p>Comparta el contexto básico del proyecto. Al enviar el formulario se abrirá WhatsApp con la información preparada; usted podrá revisarla antes de enviarla.</p><div className="contact-links"><a href="tel:+526313185564"><Phone />631 318 5564</a><a href="mailto:sginogales@gmail.com"><Mail />sginogales@gmail.com</a><a href="https://www.google.com/maps/dir/?api=1&destination=31.3236,-110.9340" target="_blank" rel="noreferrer"><MapPin />Lago Azul #45, Jardín de la Montaña, Nogales, Sonora</a></div></div><form onSubmit={sendRequest}><label>Nombre<input name="name" autoComplete="name" required minLength={2} /></label><label>Empresa<input name="company" autoComplete="organization" /></label><label>Correo<input name="email" type="email" autoComplete="email" required /></label><label>Teléfono<input name="phone" type="tel" autoComplete="tel" /></label><label>Servicio<select name="service" required defaultValue=""><option value="" disabled>Seleccione una opción</option>{services.map(s => <option key={s.title}>{s.title}</option>)}</select></label><label className="full">Necesidad<textarea name="message" required minLength={10} rows={5} placeholder="Equipo, área, falla, alcance o fecha requerida" /></label><p className="privacy full">Usaremos estos datos únicamente para atender su solicitud. El mensaje no se envía hasta que usted lo confirme en WhatsApp.</p><button className="button primary full" type="submit">Preparar solicitud en WhatsApp</button></form></section>
    </main>
    <footer><img src={asset("/logo-sgi.png")} alt="" /><p>SGI · Servicios Generales de Ingeniería<br />Nogales, Sonora, México</p><div><a href="#servicios">Servicios</a><a href="#proyectos">Proyectos</a><a href="#contacto">Contacto</a></div><small>© {new Date().getFullYear()} SGI. La disponibilidad y los tiempos de atención se confirman para cada solicitud.</small></footer><a className="floating-whatsapp" href={`${whatsapp}?text=${encodeURIComponent("Hola SGI, necesito información sobre sus servicios.")}`} target="_blank" rel="noreferrer" aria-label="Contactar a SGI por WhatsApp">WA</a>
  </div>;
}
export default App;
