// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/sgi-variants/CinematicDark.tsx": () => import("../components/mockups/sgi-variants/CinematicDark.tsx"),
  "./components/mockups/sgi-variants/CorporateClean.tsx": () => import("../components/mockups/sgi-variants/CorporateClean.tsx"),
  "./components/mockups/sgi-variants/DiagonalAccent.tsx": () => import("../components/mockups/sgi-variants/DiagonalAccent.tsx"),
  "./components/mockups/sgi-variants/IndustrialBold.tsx": () => import("../components/mockups/sgi-variants/IndustrialBold.tsx")
};
